[workspace]
resolver = "2"
members = [
	"gmcl_rekinect",
	"kinect",
	"rekinector",
	"kinect-winsdk-v1",
	"kinect-winsdk-v2",
]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
lto = "thin"
opt-level = 3
codegen-units = 1
strip = true
