[package]
name = "kinect-v1"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
windows = { version = "0.52", features = [
	"Win32_Foundation",
	"Win32_UI",
	"Win32_UI_WindowsAndMessaging",
] }

[build-dependencies]
cc = "1"
build_cfg = "1"
