[package]
name = "kinect"
version = "0.1.0"
edition = "2021"
publish = false

[[bin]]
path = "src/main.rs"
name = "gmcl_rekinect_test"

[dependencies]
ctrlc = "3"
libloading = "0.8"
log = "0.4"
env_logger = "0.10"
