name: build

on:
  push:
    tags:
      - 'v*.*.*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build_windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1

    - name: Install Rust
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- --default-toolchain nightly --profile minimal -y
        rustup target add i686-pc-windows-msvc

    - name: Build
      run: cargo build --release --target x86_64-pc-windows-msvc --target i686-pc-windows-msvc --package rekinector --package gmcl_rekinect --package rekinect_winsdk_v1 --package rekinect_winsdk_v2

    - name: Rename binaries
      run: |
        mkdir release\bin
        mkdir release\gmcl_rekinect

        mv target\i686-pc-windows-msvc\release\rekinector.exe release\bin\rekinector_win32.exe
        mv target\i686-pc-windows-msvc\release\gmcl_rekinect.dll release\gmcl_rekinect\gmcl_rekinect_win32.dll
        mv target\i686-pc-windows-msvc\release\rekinect_winsdk_v2.dll release\gmcl_rekinect\rekinect_winsdk_v2_win32.dll
        mv target\i686-pc-windows-msvc\release\rekinect_winsdk_v1.dll release\gmcl_rekinect\rekinect_winsdk_v1_win32.dll

        mv target\x86_64-pc-windows-msvc\release\rekinector.exe release\bin\rekinector_win64.exe
        mv target\x86_64-pc-windows-msvc\release\gmcl_rekinect.dll release\gmcl_rekinect\gmcl_rekinect_win64.dll
        mv target\x86_64-pc-windows-msvc\release\rekinect_winsdk_v2.dll release\gmcl_rekinect\rekinect_winsdk_v2_win64.dll
        mv target\x86_64-pc-windows-msvc\release\rekinect_winsdk_v1.dll release\gmcl_rekinect\rekinect_winsdk_v1_win64.dll

    - name: Create archive
      run: powershell Compress-Archive release/gmcl_rekinect/* release/bin/gmcl_rekinect_win.zip

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          release/bin/gmcl_rekinect_win.zip
          release/bin/rekinector_win32.exe
          release/bin/rekinector_win64.exe